import { 
  UserProfile, 
  Student, 
  Faculty, 
  Department, 
  Course, 
  Subject, 
  AcademicClass, 
  AttendanceSession, 
  AttendanceRecord, 
  TimetableEntry, 
  NotificationItem, 
  AuditLog, 
  SystemSettings 
} from '../types';

export const INITIAL_SETTINGS: SystemSettings = {
  minAttendanceThreshold: 75,
  qrRotationIntervalSeconds: 3,
  faceConfidenceThreshold: 0.72,
  allowManualCorrection: true,
  academicTerm: 'Fall 2026 - Semester VI',
};

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'admin-01',
    email: 'admin@smartattend.edu',
    role: 'ADMIN',
    fullName: 'Dr. Sarah Jenkins',
    phone: '+1 (555) 019-2831',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'faculty-01',
    email: 'faculty@smartattend.edu',
    role: 'FACULTY',
    fullName: 'Prof. Vikram Sharma',
    phone: '+1 (555) 018-9942',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    departmentId: 'dept-aiml',
    createdAt: '2026-01-15T09:30:00Z',
  },
  {
    id: 'stu-nandini',
    email: 'nandini@smartattend.edu',
    role: 'STUDENT',
    fullName: 'nandini',
    phone: '+1 (555) 014-9923',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    departmentId: 'dept-aiml',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'stu-01',
    email: 'student@smartattend.edu',
    role: 'STUDENT',
    fullName: 'Rahul Patil',
    phone: '+1 (555) 014-5521',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    departmentId: 'dept-aiml',
    createdAt: '2026-02-01T10:00:00Z',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept-aiml', name: 'Artificial Intelligence & Machine Learning', code: 'AIML', totalStudents: 120, totalFaculty: 8 },
  { id: 'dept-cse', name: 'Computer Science & Engineering', code: 'CSE', totalStudents: 240, totalFaculty: 15 },
  { id: 'dept-it', name: 'Information Technology', code: 'IT', totalStudents: 180, totalFaculty: 12 },
];

export const INITIAL_COURSES: Course[] = [
  { id: 'course-aiml', departmentId: 'dept-aiml', name: 'B.Tech Artificial Intelligence & Machine Learning', code: 'BTECH-AIML', durationYears: 4 },
  { id: 'course-cse', departmentId: 'dept-cse', name: 'B.Tech Computer Science & Engineering', code: 'BTECH-CSE', durationYears: 4 },
  { id: 'course-it', departmentId: 'dept-it', name: 'B.Tech Information Technology', code: 'BTECH-IT', durationYears: 4 },
];

export const INITIAL_SUBJECTS: Subject[] = [
  { id: 'sub-ml', name: 'Machine Learning', code: 'AIML-501', departmentId: 'dept-aiml', courseId: 'course-aiml', semester: 6, credits: 4 },
  { id: 'sub-ds', name: 'Data Science', code: 'AIML-502', departmentId: 'dept-aiml', courseId: 'course-aiml', semester: 6, credits: 4 },
  { id: 'sub-py', name: 'Python Programming', code: 'AIML-503', departmentId: 'dept-aiml', courseId: 'course-aiml', semester: 6, credits: 3 },
  { id: 'sub-wt', name: 'Web Technology', code: 'AIML-504', departmentId: 'dept-aiml', courseId: 'course-aiml', semester: 6, credits: 3 },
];

export const INITIAL_CLASSES: AcademicClass[] = [
  { id: 'cls-aiml-3a', name: 'B.Tech AIML - Year 3 - Div A', courseId: 'course-aiml', year: 3, division: 'A', roomNumber: 'Room A-204', totalStudents: 48 },
  { id: 'cls-aiml-3b', name: 'B.Tech AIML - Year 3 - Div B', courseId: 'course-aiml', year: 3, division: 'B', roomNumber: 'Room A-205', totalStudents: 46 },
  { id: 'cls-cse-3a', name: 'B.Tech CSE - Year 3 - Div A', courseId: 'course-cse', year: 3, division: 'A', roomNumber: 'Room C-301', totalStudents: 60 },
];

export const INITIAL_FACULTY: Faculty[] = [
  {
    id: 'faculty-01',
    facultyId: 'FAC-101',
    fullName: 'Prof. Vikram Sharma',
    email: 'faculty@smartattend.edu',
    phone: '+1 (555) 018-9942',
    departmentId: 'dept-aiml',
    departmentName: 'Artificial Intelligence & Machine Learning',
    designation: 'Associate Professor',
    assignedSubjects: ['sub-ml', 'sub-py'],
    assignedClasses: ['cls-aiml-3a'],
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    status: 'ACTIVE',
  },
  {
    id: 'faculty-02',
    facultyId: 'FAC-102',
    fullName: 'Dr. Ananya Iyer',
    email: 'ananya.iyer@smartattend.edu',
    phone: '+1 (555) 019-3321',
    departmentId: 'dept-aiml',
    departmentName: 'Artificial Intelligence & Machine Learning',
    designation: 'Head of Department & Professor',
    assignedSubjects: ['sub-ds', 'sub-wt'],
    assignedClasses: ['cls-aiml-3a', 'cls-aiml-3b'],
    profileImage: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    status: 'ACTIVE',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu-nandini',
    studentId: 'STU-2026-023',
    fullName: 'nandini',
    email: 'nandini@smartattend.edu',
    phone: '+1 (555) 014-9923',
    departmentId: 'dept-aiml',
    departmentName: 'AIML',
    courseId: 'course-aiml',
    courseName: 'B.Tech AIML',
    year: 3,
    division: 'A',
    rollNumber: '23',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    status: 'ACTIVE',
    faceEnrolled: true,
    faceEnrolledAt: '2026-02-14T10:00:00Z',
    overallAttendance: 100,
  },
  {
    id: 'stu-01',
    studentId: 'STU-2026-001',
    fullName: 'Rahul Patil',
    email: 'student@smartattend.edu',
    phone: '+1 (555) 014-5521',
    departmentId: 'dept-aiml',
    departmentName: 'AIML',
    courseId: 'course-aiml',
    courseName: 'B.Tech AIML',
    year: 3,
    division: 'A',
    rollNumber: '101',
    profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    status: 'ACTIVE',
    faceEnrolled: true,
    faceEnrolledAt: '2026-02-10T14:20:00Z',
    overallAttendance: 87.4,
  },
  {
    id: 'stu-02',
    studentId: 'STU-2026-002',
    fullName: 'Sneha Mane',
    email: 'sneha.m@smartattend.edu',
    phone: '+1 (555) 014-5522',
    departmentId: 'dept-aiml',
    departmentName: 'AIML',
    courseId: 'course-aiml',
    courseName: 'B.Tech AIML',
    year: 3,
    division: 'A',
    rollNumber: '102',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    status: 'ACTIVE',
    faceEnrolled: true,
    faceEnrolledAt: '2026-02-11T11:00:00Z',
    overallAttendance: 91.2,
  },
  {
    id: 'stu-03',
    studentId: 'STU-2026-003',
    fullName: 'Aditya Joshi',
    email: 'aditya.j@smartattend.edu',
    phone: '+1 (555) 014-5523',
    departmentId: 'dept-aiml',
    departmentName: 'AIML',
    courseId: 'course-aiml',
    courseName: 'B.Tech AIML',
    year: 3,
    division: 'A',
    rollNumber: '103',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    status: 'ACTIVE',
    faceEnrolled: true,
    faceEnrolledAt: '2026-02-12T09:15:00Z',
    overallAttendance: 84.5,
  },
  {
    id: 'stu-04',
    studentId: 'STU-2026-004',
    fullName: 'Priya Shah',
    email: 'priya.s@smartattend.edu',
    phone: '+1 (555) 014-5524',
    departmentId: 'dept-aiml',
    departmentName: 'AIML',
    courseId: 'course-aiml',
    courseName: 'B.Tech AIML',
    year: 3,
    division: 'A',
    rollNumber: '104',
    profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    status: 'ACTIVE',
    faceEnrolled: false,
    overallAttendance: 76.0,
  },
  {
    id: 'stu-05',
    studentId: 'STU-2026-005',
    fullName: 'Karan Patil',
    email: 'karan.p@smartattend.edu',
    phone: '+1 (555) 014-5525',
    departmentId: 'dept-aiml',
    departmentName: 'AIML',
    courseId: 'course-aiml',
    courseName: 'B.Tech AIML',
    year: 3,
    division: 'A',
    rollNumber: '105',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    status: 'ACTIVE',
    faceEnrolled: true,
    faceEnrolledAt: '2026-02-15T16:00:00Z',
    overallAttendance: 68.0, // Low attendance flag
  },
  {
    id: 'stu-06',
    studentId: 'STU-2026-006',
    fullName: 'Rohan Sharma',
    email: 'rohan.s@smartattend.edu',
    phone: '+1 (555) 014-5526',
    departmentId: 'dept-aiml',
    departmentName: 'AIML',
    courseId: 'course-aiml',
    courseName: 'B.Tech AIML',
    year: 3,
    division: 'A',
    rollNumber: '106',
    profileImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    status: 'ACTIVE',
    faceEnrolled: false,
    overallAttendance: 72.5, // Low attendance flag
  },
];

export const INITIAL_TIMETABLE: TimetableEntry[] = [
  {
    id: 'tt-1',
    day: 'MONDAY',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    subjectId: 'sub-ml',
    subjectName: 'Machine Learning',
    facultyId: 'faculty-01',
    facultyName: 'Prof. Vikram Sharma',
    classId: 'cls-aiml-3a',
    className: 'B.Tech AIML - Div A',
    division: 'A',
    roomNumber: 'Room A-204',
  },
  {
    id: 'tt-2',
    day: 'MONDAY',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    subjectId: 'sub-ds',
    subjectName: 'Data Science',
    facultyId: 'faculty-02',
    facultyName: 'Dr. Ananya Iyer',
    classId: 'cls-aiml-3a',
    className: 'B.Tech AIML - Div A',
    division: 'A',
    roomNumber: 'Room A-204',
  },
  {
    id: 'tt-3',
    day: 'MONDAY',
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    subjectId: 'sub-py',
    subjectName: 'Python Programming',
    facultyId: 'faculty-01',
    facultyName: 'Prof. Vikram Sharma',
    classId: 'cls-aiml-3a',
    className: 'B.Tech AIML - Div A',
    division: 'A',
    roomNumber: 'Lab L-102',
  },
  {
    id: 'tt-4',
    day: 'TUESDAY',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    subjectId: 'sub-wt',
    subjectName: 'Web Technology',
    facultyId: 'faculty-02',
    facultyName: 'Dr. Ananya Iyer',
    classId: 'cls-aiml-3a',
    className: 'B.Tech AIML - Div A',
    division: 'A',
    roomNumber: 'Room A-204',
  },
  {
    id: 'tt-5',
    day: 'TUESDAY',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    subjectId: 'sub-ml',
    subjectName: 'Machine Learning',
    facultyId: 'faculty-01',
    facultyName: 'Prof. Vikram Sharma',
    classId: 'cls-aiml-3a',
    className: 'B.Tech AIML - Div A',
    division: 'A',
    roomNumber: 'Room A-204',
  },
];

export const INITIAL_SESSIONS: AttendanceSession[] = [
  {
    id: 'sess-active-01',
    facultyId: 'faculty-01',
    facultyName: 'Prof. Vikram Sharma',
    subjectId: 'sub-ml',
    subjectName: 'Machine Learning',
    classId: 'cls-aiml-3a',
    className: 'B.Tech AIML - Year 3 - Div A',
    division: 'A',
    date: '2026-09-30',
    startTime: '2026-09-30T09:00:00Z',
    endTime: '2026-09-30T10:00:00Z',
    durationMinutes: 60,
    method: 'QR',
    status: 'ACTIVE',
    totalStudents: 48,
    presentCount: 38,
    roomNumber: 'Room A-204',
  },
  {
    id: 'sess-past-02',
    facultyId: 'faculty-01',
    facultyName: 'Prof. Vikram Sharma',
    subjectId: 'sub-py',
    subjectName: 'Python Programming',
    classId: 'cls-aiml-3a',
    className: 'B.Tech AIML - Year 3 - Div A',
    division: 'A',
    date: '2026-09-29',
    startTime: '2026-09-29T11:15:00Z',
    endTime: '2026-09-29T12:15:00Z',
    durationMinutes: 60,
    method: 'FACE',
    status: 'COMPLETED',
    totalStudents: 48,
    presentCount: 44,
    roomNumber: 'Lab L-102',
  },
  {
    id: 'sess-past-03',
    facultyId: 'faculty-02',
    facultyName: 'Dr. Ananya Iyer',
    subjectId: 'sub-ds',
    subjectName: 'Data Science',
    classId: 'cls-aiml-3a',
    className: 'B.Tech AIML - Year 3 - Div A',
    division: 'A',
    date: '2026-09-28',
    startTime: '2026-09-28T10:00:00Z',
    endTime: '2026-09-28T11:00:00Z',
    durationMinutes: 60,
    method: 'QR',
    status: 'COMPLETED',
    totalStudents: 48,
    presentCount: 40,
    roomNumber: 'Room A-204',
  }
];

export const INITIAL_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: 'rec-01',
    sessionId: 'sess-active-01',
    studentId: 'stu-01',
    studentName: 'Rahul Patil',
    rollNumber: '101',
    subjectId: 'sub-ml',
    subjectName: 'Machine Learning',
    classId: 'cls-aiml-3a',
    division: 'A',
    facultyId: 'faculty-01',
    date: '2026-09-30',
    timestamp: '2026-09-30T09:05:14Z',
    recordedTime: '09:05 AM',
    method: 'QR',
    status: 'PRESENT',
  },
  {
    id: 'rec-02',
    sessionId: 'sess-active-01',
    studentId: 'stu-02',
    studentName: 'Sneha Mane',
    rollNumber: '102',
    subjectId: 'sub-ml',
    subjectName: 'Machine Learning',
    classId: 'cls-aiml-3a',
    division: 'A',
    facultyId: 'faculty-01',
    date: '2026-09-30',
    timestamp: '2026-09-30T09:06:22Z',
    recordedTime: '09:06 AM',
    method: 'QR',
    status: 'PRESENT',
  },
  {
    id: 'rec-03',
    sessionId: 'sess-active-01',
    studentId: 'stu-03',
    studentName: 'Aditya Joshi',
    rollNumber: '103',
    subjectId: 'sub-ml',
    subjectName: 'Machine Learning',
    classId: 'cls-aiml-3a',
    division: 'A',
    facultyId: 'faculty-01',
    date: '2026-09-30',
    timestamp: '2026-09-30T09:07:05Z',
    recordedTime: '09:07 AM',
    method: 'QR',
    status: 'PRESENT',
  },
  {
    id: 'rec-04',
    sessionId: 'sess-past-02',
    studentId: 'stu-01',
    studentName: 'Rahul Patil',
    rollNumber: '101',
    subjectId: 'sub-py',
    subjectName: 'Python Programming',
    classId: 'cls-aiml-3a',
    division: 'A',
    facultyId: 'faculty-01',
    date: '2026-09-29',
    timestamp: '2026-09-29T11:18:40Z',
    recordedTime: '11:18 AM',
    method: 'FACE',
    status: 'PRESENT',
    confidence: 0.96,
  },
  {
    id: 'rec-05',
    sessionId: 'sess-past-03',
    studentId: 'stu-05',
    studentName: 'Karan Patil',
    rollNumber: '105',
    subjectId: 'sub-ds',
    subjectName: 'Data Science',
    classId: 'cls-aiml-3a',
    division: 'A',
    facultyId: 'faculty-02',
    date: '2026-09-28',
    timestamp: '2026-09-28T10:00:00Z',
    recordedTime: '10:00 AM',
    method: 'QR',
    status: 'ABSENT',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'stu-01',
    title: 'Attendance Marked',
    message: 'Your attendance was successfully marked for Machine Learning via Dynamic QR.',
    type: 'SUCCESS',
    read: false,
    createdAt: '2026-09-30T09:05:15Z',
  },
  {
    id: 'notif-2',
    userId: 'stu-05',
    title: 'Low Attendance Warning',
    message: 'Your overall attendance is 68.0%, below the mandatory 75% threshold.',
    type: 'WARNING',
    read: false,
    createdAt: '2026-09-29T15:00:00Z',
  },
  {
    id: 'notif-3',
    targetRole: 'ALL',
    title: 'Semester Midterm Schedule',
    message: 'Midterm assessments commence from next Monday. Please review subject attendance criteria.',
    type: 'INFO',
    read: true,
    createdAt: '2026-09-28T09:00:00Z',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-09-30T09:00:00Z',
    actorId: 'faculty-01',
    actorName: 'Prof. Vikram Sharma',
    actorRole: 'FACULTY',
    action: 'STARTED_ATTENDANCE_SESSION',
    details: 'Started Dynamic QR attendance for Machine Learning (B.Tech AIML - Div A)',
    ipAddress: '192.168.1.104',
  },
  {
    id: 'log-2',
    timestamp: '2026-09-30T09:05:14Z',
    actorId: 'stu-01',
    actorName: 'Rahul Patil',
    actorRole: 'STUDENT',
    action: 'ATTENDANCE_MARKED',
    details: 'Student marked attendance via Dynamic QR (Token validated in 1.4s)',
    ipAddress: '192.168.1.218',
  },
  {
    id: 'log-3',
    timestamp: '2026-09-29T11:18:40Z',
    actorId: 'faculty-01',
    actorName: 'Prof. Vikram Sharma',
    actorRole: 'FACULTY',
    action: 'FACE_RECOGNITION_VERIFIED',
    details: 'Biometric AI matched Rahul Patil with 96% confidence score',
    ipAddress: '192.168.1.104',
  },
  {
    id: 'log-4',
    timestamp: '2026-09-29T08:30:00Z',
    actorId: 'admin-01',
    actorName: 'Dr. Sarah Jenkins',
    actorRole: 'ADMIN',
    action: 'STUDENT_ENROLLED',
    details: 'Registered new student record STU-2026-006 (Rohan Sharma)',
    ipAddress: '192.168.1.10',
  }
];
